Repository Ogu-Family/MIML_backend, pull requests merged in 2023-12, with the labels that each got.

#4 feat #1: 기본 엔티티 생성
  src/main/java/com/miml/c2k/domain/member/Member.java
  src/main/java/com/miml/c2k/domain/movie/Movie.java
  src/main/java/com/miml/c2k/domain/payment/Payment.java
  src/main/java/com/miml/c2k/domain/schedule/Schedule.java
  src/main/java/com/miml/c2k/domain/screen/Screen.java
  src/main/java/com/miml/c2k/domain/seat/Seat.java
  src/main/java/com/miml/c2k/domain/theater/Theater.java
  src/main/java/com/miml/c2k/domain/ticket/Ticket.java
Labels: feat, 리뷰 얼마 안걸려요!

#10 feat #6: 영화 상영 일정 추가 관리자 페이지 추가
  src/main/java/com/miml/c2k/domain/admin/controller/AdminController.java
  src/main/java/com/miml/c2k/domain/admin/dto/MovieAdminResponseDto.java
  src/main/java/com/miml/c2k/domain/movie/service/MovieService.java
  src/main/java/com/miml/c2k/domain/schedule/Schedule.java
  src/main/java/com/miml/c2k/domain/schedule/dto/ScheduleSavingDto.java
  src/main/java/com/miml/c2k/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/miml/c2k/domain/schedule/service/ScheduleService.java
  src/main/java/com/miml/c2k/domain/screen/Screen.java
  src/main/java/com/miml/c2k/domain/screen/controller/ScreenAdminController.java
  src/main/java/com/miml/c2k/domain/screen/dto/ScreenAdminResponseDto.java
  src/main/java/com/miml/c2k/domain/screen/repository/ScreenRepository.java
  src/main/java/com/miml/c2k/domain/screen/service/ScreenService.java
  src/main/java/com/miml/c2k/domain/theater/Theater.java
  src/main/java/com/miml/c2k/domain/theater/controller/TheaterController.java
  src/main/java/com/miml/c2k/domain/theater/dto/TheaterAdminResponseDto.java
  src/main/java/com/miml/c2k/domain/theater/repository/TheaterRepository.java
  src/main/java/com/miml/c2k/domain/theater/service/TheaterService.java
  src/main/resources/static/default.png
  src/main/resources/templates/admin/admin-schedule.html
Labels: feat, 리뷰 급합니다!!!

#7 feat #2: 현재 상영중인 영화 목록 반환 및 영화 등록 기능 구현
  build.gradle
  src/main/java/com/miml/c2k/App.java
  src/main/java/com/miml/c2k/domain/admin/controller/AdminController.java
  src/main/java/com/miml/c2k/domain/admin/dto/MovieAdminResponseDto.java
  src/main/java/com/miml/c2k/domain/member/Member.java
  src/main/java/com/miml/c2k/domain/movie/Movie.java
  src/main/java/com/miml/c2k/domain/movie/controller/MovieController.java
  src/main/java/com/miml/c2k/domain/movie/dto/MovieResponseDto.java
  src/main/java/com/miml/c2k/domain/movie/dto/PlayingStatusType.java
  src/main/java/com/miml/c2k/domain/movie/repository/MovieRepository.java
  src/main/java/com/miml/c2k/domain/movie/service/MovieService.java
  src/main/java/com/miml/c2k/domain/payment/Payment.java
  src/main/java/com/miml/c2k/domain/schedule/Schedule.java
  src/main/java/com/miml/c2k/domain/schedule/dto/ScheduleSavingDto.java
  src/main/java/com/miml/c2k/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/miml/c2k/domain/schedule/service/ScheduleService.java
  src/main/java/com/miml/c2k/domain/screen/Screen.java
  src/main/java/com/miml/c2k/domain/screen/dto/ScreenAdminResponseDto.java
  src/main/java/com/miml/c2k/domain/seat/Seat.java
  src/main/java/com/miml/c2k/domain/theater/Theater.java
  src/main/java/com/miml/c2k/domain/theater/dto/TheaterAdminResponseDto.java
  src/main/java/com/miml/c2k/domain/ticket/Ticket.java
  src/main/java/com/miml/c2k/util/KobisOpenApiUtil.java
Labels: feat, 리뷰 천천해 해주세요~

#9 feat #3: kakao login api를 사용하여 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/miml/c2k/domain/member/Member.java
  src/main/java/com/miml/c2k/domain/member/OAuthProvider.java
  src/main/java/com/miml/c2k/domain/member/controller/MemberController.java
  src/main/java/com/miml/c2k/domain/member/repository/MemberRepository.java
  src/main/java/com/miml/c2k/global/auth/ClientConfig.java
  src/main/java/com/miml/c2k/global/auth/OAuthController.java
  src/main/java/com/miml/c2k/global/auth/OAuthLoginService.java
  src/main/java/com/miml/c2k/global/auth/RequestOAuthInfoService.java
  src/main/java/com/miml/c2k/global/auth/SecurityConfig.java
  src/main/java/com/miml/c2k/global/auth/jwt/AuthTokens.java
  src/main/java/com/miml/c2k/global/auth/jwt/AuthTokensGenerator.java
  src/main/java/com/miml/c2k/global/auth/jwt/JwtProvider.java
  src/main/java/com/miml/c2k/global/auth/platform/OAuthApiClient.java
  src/main/java/com/miml/c2k/global/auth/platform/OAuthInfoResponse.java
  src/main/java/com/miml/c2k/global/auth/platform/OAuthLoginParams.java
  src/main/java/com/miml/c2k/global/auth/platform/kakao/KakaoApiClient.java
  src/main/java/com/miml/c2k/global/auth/platform/kakao/KakaoInfoResponse.java
  src/main/java/com/miml/c2k/global/auth/platform/kakao/KakaoLoginParams.java
  src/main/java/com/miml/c2k/global/auth/platform/kakao/KakaoTokens.java
Labels: feat, 리뷰 천천해 해주세요~

#15 Feat #11: 영화 선택 페이지 추가
  src/main/java/com/miml/c2k/domain/admin/controller/AdminController.java
  src/main/java/com/miml/c2k/domain/schedule/controller/ScheduleController.java
  src/main/java/com/miml/c2k/domain/schedule/dto/ScheduleViewResponseDto.java
  src/main/java/com/miml/c2k/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/miml/c2k/domain/schedule/service/ScheduleService.java
  src/main/java/com/miml/c2k/domain/seat/repository/SeatRepository.java
  src/main/resources/static/css/common.css
  src/main/resources/templates/admin/admin-schedule.html
  src/main/resources/templates/schedule/select-schedule.html
Labels: feat, 리뷰 천천해 해주세요~

#13 feat #8, #6: 상영예정작 API 구현 및 타임리프 페이지 추가
  src/main/java/com/miml/c2k/domain/admin/controller/AdminController.java
  src/main/java/com/miml/c2k/domain/movie/Movie.java
  src/main/java/com/miml/c2k/domain/movie/controller/MovieController.java
  src/main/java/com/miml/c2k/domain/movie/dto/MovieResponseDto.java
  src/main/java/com/miml/c2k/domain/movie/dto/PlayingStatusType.java
  src/main/java/com/miml/c2k/domain/movie/repository/MovieRepository.java
  src/main/java/com/miml/c2k/domain/movie/service/MovieService.java
  src/main/java/com/miml/c2k/util/KobisOpenApiUtil.java
  src/main/resources/templates/admin/insert-movie.html
  src/main/resources/templates/member/movie-list.html
Labels: feat, 리뷰 얼마 안걸려요!
